apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-assistant.fullname" . }}
  labels:
    {{- include "rag-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rag-assistant.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
